/// The onboarding personalized note plus a forward-looking "~2 weeks" outlook,
/// generated by the backend. [outlook] may be null even when [narrative] is set.
class CatNarrative {
  final String narrative;
  final String? outlook;

  const CatNarrative({required this.narrative, this.outlook});
}
