/// A short quality verdict for a cat-food brand the owner currently feeds,
/// generated by the `analyzeBrand` backend (grounded by our catalog when we
/// have data for the brand).
class BrandVerdict {
  /// 0-100 overall quality rating for the brand's typical food.
  final int score;
  final String headline;

  /// 2-4 concise critique points (ingredient/nutrition focused).
  final List<String> reasons;

  /// 0-2 fair positive points, if any.
  final List<String> positives;

  const BrandVerdict({
    required this.score,
    required this.headline,
    required this.reasons,
    this.positives = const [],
  });
}

/// Our own catalog grounding for a brand: average re-graded score + the most
/// common cons across its products. Empty when the brand isn't in our index.
class BrandCatalogContext {
  final double avgScore;
  final int productCount;
  final List<String> topCons;

  const BrandCatalogContext({
    required this.avgScore,
    required this.productCount,
    required this.topCons,
  });
}
